//
//  NewMessagePresenter.swift
//  RealTimeChat
//
//  Created by Manuel Salvador del Águila on 17/06/2019.
//  Copyright (c) 2019 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewMessagePresentationLogic
{
    func presentSomething(response: NewMessage.Something.Response)
    func presentUsersLoaded(response: NewMessage.LoadAvailableUsers.Response)
    func userTapped(response: NewMessage.TappedOnUser.Response)
}

class NewMessagePresenter: NewMessagePresentationLogic
{
    weak var viewController: NewMessageDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: NewMessage.Something.Response)
    {
        let viewModel = NewMessage.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentUsersLoaded(response: NewMessage.LoadAvailableUsers.Response) {
        let viewModel = NewMessage.LoadAvailableUsers.ViewModel(users: response.users)
        viewController?.displayLoadedUsers(viewModel: viewModel)
    }
    
    func userTapped(response: NewMessage.TappedOnUser.Response) {
        let viewModel = NewMessage.TappedOnUser.ViewModel()
        viewController?.userHasBeenSavedAfterTapping(viewModel: viewModel)
    }
}
