//
//  ChatLogWorker.swift
//  RealTimeChat
//
//  Created by Manuel Salvador del Águila on 26/06/2019.
//  Copyright (c) 2019 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ChatLogWorker
{
    
    var repository = Repository.getInstance()
    
    func doSomeWork()
    {
    }
    
    func sendMessage(request: ChatLog.SendMessage.Request, completion: @escaping() -> Void) {
        repository.sendMessage(message: request.message) {
            completion()
        }
    }
}
