//
//  ChatLogPresenter.swift
//  RealTimeChat
//
//  Created by Manuel Salvador del Águila on 26/06/2019.
//  Copyright (c) 2019 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatLogPresentationLogic
{
    func presentSomething(response: ChatLog.Something.Response)
    func messageSent(response: ChatLog.SendMessage.Response)
}

class ChatLogPresenter: ChatLogPresentationLogic
{
    weak var viewController: ChatLogDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ChatLog.Something.Response)
    {
        let viewModel = ChatLog.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func messageSent(response: ChatLog.SendMessage.Response) {
        let viewModel = ChatLog.SendMessage.ViewModel()
        viewController?.messageSent(viewModel: viewModel)
    }
}
