//
//  HomePresenter.swift
//  RealTimeChat
//
//  Created by Manuel Salvador del Águila on 16/06/2019.
//  Copyright (c) 2019 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentSomething(response: Home.Something.Response)
    func isUserLoggedIn(response: Home.IsUserLoggedIn.Response)
    func logoutUser(response: Home.LogoutUser.Response)
    func getCurrentUser(response: Home.GetCurrentUserLoggedIn.Response)
    func loadMessages(response: Home.LoadMessages.Response)
}

class HomePresenter: HomePresentationLogic
{
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Home.Something.Response)
    {
        let viewModel = Home.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func isUserLoggedIn(response: Home.IsUserLoggedIn.Response) {
        let viewModel = Home.IsUserLoggedIn.ViewModel(isLogged: response.isLogged)
        viewController?.displayIsUserLoggedIn(viewModel: viewModel)
    }
    
    func logoutUser(response: Home.LogoutUser.Response) {
        let viewModel = Home.LogoutUser.ViewModel()
        viewController?.displayLogoutUser(viewModel: viewModel)
    }
    
    func getCurrentUser(response: Home.GetCurrentUserLoggedIn.Response) {
        let viewModel = Home.GetCurrentUserLoggedIn.ViewModel(user: response.user)
        viewController?.displayCurrentUser(viewModel: viewModel)
    }
    
    func loadMessages(response: Home.LoadMessages.Response) {
        let viewModel = Home.LoadMessages.ViewModel(messages: response.messages)
        viewController?.displayMessages(viewModel: viewModel)
    }
}
