//
//  HomeModels.swift
//  RealTimeChat
//
//  Created by Manuel Salvador del Águila on 16/06/2019.
//  Copyright (c) 2019 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    enum IsUserLoggedIn
    {
        struct Request
        {
        }
        struct Response
        {
            var isLogged: Bool
        }
        struct ViewModel
        {
            var isLogged: Bool
        }
    }
    
    enum LogoutUser
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    enum GetCurrentUserLoggedIn
    {
        struct Request
        {
        }
        struct Response
        {
            var user: UserClass
        }
        struct ViewModel
        {
            var user: UserClass
        }
    }
    
    enum LoadHomeMessages
    {
        struct Request
        {
        }
        struct Response
        {
            var messages: [HomeMessage]
        }
        struct ViewModel
        {
            var messages: [HomeMessage]
        }
    }

}
