//
//  LoginModels.swift
//  RealTimeChat
//
//  Created by Manuel Salvador del Águila on 16/06/2019.
//  Copyright (c) 2019 Manuel Salvador del Águila. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    enum RegisterButtonPressed
    {
        struct Request
        {
            var name: String
            var email: String
            var password: String
            var profileImage: UIImage
        }
        struct Response
        {
            var error: Bool
            var passwordTooShort: Bool
        }
        struct ViewModel
        {
            var error: Bool
            var passwordTooShort: Bool
        }
    }
    
    enum LoginButtonPressed
    {
        struct Request
        {
            var email: String
            var password: String
        }
        struct Response
        {
            var error: Bool
            var passwordTooShort: Bool
        }
        struct ViewModel
        {
            var error: Bool
            var passwordTooShort: Bool
        }
    }
    
}
